---
#Adding GPG key 
- name: Add PHP 7.4 apt key
  apt_key: 
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
  
#Adding repository 
- name: Add PHP "{{ php_version }}" repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ stretch main"
    state: present
    filename: 'php{{ php_version }}'

- name: Install PHP "{{ php_version }}"
  apt: 
    name: "{{ packages }}" 
    state: present
  vars:
    packages:
        - "python-mysqldb"
        - "libcurl3"
        - "php{{ php_version }}"
        - "php{{ php_version }}-fpm"
        - "php{{ php_version }}-mysql"
        - "php{{ php_version }}-xml"
        - "php{{ php_version }}-curl"
        - "php{{ php_version }}-gd"
        - "php{{ php_version }}-mbstring"
        - "php{{ php_version }}-zip"
    
